#= require jquery
#= require jquery_ujs
#= require d3
#= require select2
#= require_tree .

window.skillsTable = (data) ->
  rowHeight = 20
  width = 600

  svg = prepareSVG(width, 300, '.svg-table')
  row = svg.selectAll('g')
        .data(data)
        .enter()
        .append('g')
        .attr('height', rowHeight)
        .attr('transform', (d, i) -> "translate(50, #{i*22})")

  today = new Date()
  todayString = "#{today.getFullYear()}-#{today.getMonth() + 1}-#{today.getDate()}"

  box = row.selectAll('rect').data((d) -> d.data)
    .enter()
    .append('rect')
    .attr('width', 20)
    .attr('x', (d, i) -> i * 22)
    .attr('height', '20')
    .attr "class", (d) ->
      if d.report
        "checked-box"
      else
        if d.date == todayString
          "unchecked-today-box"
        else
          "unchecked-box"

  text = svg.selectAll('text').data(data)
    .enter()
    .append('text')
    .text((d) -> d.skill)
    .attr('y', (d,i) -> (i * 23) + 11)
    .attr('x', 0)

window.visualizeWeeklyReading = (dataset, days) ->
  w = $('.container').width()
  h = 350
  barPadding = 1

  svg = prepareSVG(w, h, '.d3-weekly-reading-chart')
  svg.selectAll('rect')
    .data(dataset)
    .enter()
    .append('rect')
    .attr('class', 'bar')
    .attr('width', w / dataset
    .length - barPadding)
    .attr('height', (d) -> d * 4)
    .attr('y', (d) -> h - d)
    .attr('x', (d, i) -> i * w / dataset)
    .length

  svg.selectAll('text')
    .data(days)
    .enter()
    .append('text')
    .text((d) -> d)
    .attr('x', (d, i) -> i * w / days.length + 5)
    .attr('y', (d) -> h - 10)
    .attr('font-size', '26px')
    .attr 'fill', 'white'

window.visualizeReadPages = (dataset, pages) ->
  w = 200
  h = 40
  svg = prepareSVG(w, h, '.d3-progress-bar')
  scale = d3.scale
    .linear()
    .domain([ 0, pages ])
    .range([ 0, w ])

  svg.selectAll('rect')
    .data(dataset)
    .enter()
    .append('rect')
    .attr('class', 'bar')
    .attr('x', (d, i) -> scale d[0])
    .attr('width', (d, i) -> scale d[1] - d[0])
    .attr('height', h)

window.prepareSVG = (w, h, selector) ->
  svg = d3.select(selector).append('svg').attr('width', w).attr('height', h)
  svg

$ ->
  $('.select2-tags').each ->
    data = $(this).attr('data-tags')
    if data
      data = JSON.parse(data)
    $(this).select2
      tags: data or []
      tokenSeparators: [
        ','
        ' '
      ]
    return
  return

# ---
# generated by js2coffee 2.0.1
